export const FACILITY_SERVICES: string[] = [
  "Emergency Medicine",
  "Cardiology",
  "Neurology",
  "Neurosurgery",
  "Orthopaedics",
  "General Surgery",
  "Obstetrics & Gynaecology",
  "Paediatrics",
  "Neonatology",
  "Internal Medicine",
  "Nephrology",
  "Urology",
  "Ophthalmology",
  "ENT",
  "Dermatology",
  "Psychiatry / Mental Health",
  "Oncology",
  "Haematology",
  "Endocrinology",
  "Gastroenterology",
  "Pulmonology / Chest Medicine",
  "Rheumatology",
  "Infectious Disease",
  "Radiology / Imaging",
  "Pathology / Lab",
  "Physiotherapy",
  "Dialysis / Renal Unit",
  "Blood Bank",
  "ICU / Critical Care",
  "Burns Unit",
  "Dental / Maxillofacial",
];
